In [1]:
import pandas as pd
import numpy as np
X_bar = pd.read_csv('X.csv', header=None).values
X = X_bar[:, :10]
X.shape
#y = pd.read_csv('Y.csv', header=None).values.ravel().astype(int)

(23241, 10)

# ICA

In [2]:
from sklearn.decomposition import FastICA 
ICA = FastICA(n_components=3, tol = 1.9 * 1e-2, random_state=0) 
X_ICA = ICA.fit_transform(X)
X_ICA
# X_ICA.shape

array([[ 0.00763871, -0.00137018,  0.01104704],
       [ 0.00038129, -0.00958104, -0.00026598],
       [-0.0105466 ,  0.00736627,  0.00379075],
       ...,
       [ 0.00722366,  0.0086751 ,  0.00661737],
       [-0.00196023, -0.00822481,  0.00587402],
       [ 0.00781979, -0.00430098, -0.00065772]])

# PCA

In [11]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import scale
X = scale(X) # 标准化，标准化之后就自动根据协方差矩阵进行主成分分析了
pca = PCA(n_components=5)
X_pca = pca.fit(X)
print(sum(pca.explained_variance_ratio_))# 输出解释方差比
#print(pca.singular_values_)
#print(pca.explained_variance_) # 输出特征根
print(pca.components_) # 输出主成分

0.8326485568226013
[[-0.10212284 -0.49324632  0.08869344 -0.10180441 -0.08077562 -0.12396384
   0.45739921 -0.37723541 -0.59503608  0.02383389]
 [-0.36112718  0.14926721  0.53001836 -0.0236879   0.22007546 -0.38737267
  -0.35190535 -0.3621228   0.01778754 -0.33473632]
 [ 0.35120509 -0.07761268  0.13037446  0.65039458  0.61340523  0.14084726
   0.02151056 -0.12293237 -0.10223291  0.09214167]
 [ 0.04312123  0.06343     0.35549409 -0.2211402  -0.12764205  0.51000923
  -0.27731664 -0.36761357 -0.01517933  0.57459689]
 [-0.61219194 -0.0650302  -0.1724018   0.1849043   0.19630924 -0.29033384
   0.0208685   0.14432547  0.08553172  0.63692076]]


# SVD

In [4]:
from sklearn.decomposition import TruncatedSVD
from scipy.sparse import csr_matrix
np.random.seed(0)
svd = TruncatedSVD(n_components=3, n_iter=7, random_state=0)
svd.fit(X)
print(svd.explained_variance_ratio_)
print(svd.explained_variance_ratio_.sum())
print(svd.singular_values_)

[0.25907695 0.2154638  0.17411413]
0.6486548780513431
[245.38148593 223.77654579 201.16128884]
